app/Models/CalcModel.cs
namespace m1.Models {
    public class CalcModel {
        public readonly int X;
        public readonly int Y;
        public readonly string Sum;
        public readonly string Sub;
        public readonly string Mp;
        public readonly string Div;
        public CalcModel(int x, int y, string sum, string sub, string mp, string div) {
            X = x;
            Y = y;
            Sum = sum;
            Sub = sub;
            Mp = mp;
            Div = div;
        }
    }
}

app/Controllers/CalcServiceController.cs
using System;
using m1.Models;
using Microsoft.AspNetCore.Mvc;

namespace m1.Controllers {
    public class CalcServiceController : Controller {
        private readonly Random rand;

        private readonly int x;
        private readonly int y;

        private readonly string sum;
        private readonly string sub;
        private readonly string mp;
        private readonly string div;

        public CalcServiceController() {
            rand = new Random();

            x = rand.Next() % 11;
            y = rand.Next() % 11;

            sum = $"{x} + {y} = {x + y}";
            sub = $"{x} - {y} = {x - y}";
            mp = $"{x} * {y} = {x * y}";

            try
            {
                div = $"{x} /  {y} = {x / y}";
            }
            catch (DivideByZeroException)
            {
                div = "zero division error";
            }
        }

        public IActionResult Index() {
            return View();
        }

        public IActionResult ByModel() {
            var model = new CalcModel(x, y, sum, sub, mp, div);
            return View(model);
        }

        public IActionResult ByViewData() {
            ViewData["X"] = x;
            ViewData["Y"] = y;

            ViewData["Sum"] = sum;
            ViewData["Sub"] = sub;
            ViewData["Mp"] = mp;
            ViewData["Div"] = div;

            return View();
        }

        public IActionResult ByViewBag() {
            ViewBag.X = x;
            ViewBag.Y = y;

            ViewBag.Sum = sum;
            ViewBag.Sub = sub;
            ViewBag.Mp = mp;
            ViewBag.Div = div;

            return View();
        }

        public IActionResult ByDirect() {
            var model = new CalcModel(x, y, sum, sub, mp, div);
            return View(model);
        }
    }
}

app/Views/CalcService/ByDirect.cshtml
@{
    ViewBag.Title = "By Direct - Backend1";
}
<h1>By Direct Model</h1>

<b>Rand value first:</b> @Model.X<br/>
<b>Rand value second:</b> @Model.Y<br/>

<b>Add:</b><br />
@Model.Sum<br />

<b>Dif:</b><br />
@Model.Sub<br />

<b>Mult:</b><br/>
@Model.Mp<br />

<b>Div:</b><br/>
@Model.Div<br />

app/Views/CalcService/ByModel.cshtml
@model m1.Models.CalcModel
@{
    ViewBag.Title = "ByModel - Backend1";
}
<h1>By Model</h1>
<b>Rand value first:</b> @Model.X<br />
<b>Rand value second:</b> @Model.Y<br />

<b>Add:</b><br />
@Model.Sum<br />

<b>Dif:</b><br />
@Model.Sub<br />

<b>Mult:</b><br />
@Model.Mp<br />

<b>Div:</b><br />
@Model.Div<br />

app/Views/CalcService/ByViewBag.cshtml
@{
    ViewBag.Title = "ByViewBag - Backend1";
}
<h1>By View Bag</h1>
<b>Rand value first:</b> @ViewBag.X<br/>
<b>Rand value second:</b> @ViewBag.Y<br/>

<b>Add:</b><br/>
@ViewBag.Sum<br/>

<b>Dif:</b><br/>
@ViewBag.Sub<br/>

<b>Mult:</b><br/>
@ViewBag.Mp<br/>

<b>Div:</b><br/>
@ViewBag.Div<br/>

app/Views/CalcService/ByViewData.cshtml
@{
    ViewBag.Title = "ByViewData - Backend1";
}
<h1>By View Bag</h1>
<b>Rand value first:</b> @ViewData["X"]<br/>
<b>Rand value second:</b> @ViewData["Y"]<br/>

<b>Add:</b><br/>
@ViewData["Sum"]<br/>

<b>Dif:</b><br/>
@ViewData["Sub"]<br/>

<b>Mult:</b><br/>
@ViewData["Mp"]<br/>

<b>Div:</b><br/>
@ViewData["Div"]<br/>

app/Views/CalcService/Index.cshtml
@{
    ViewBag.Title = "Home Page - Backend1";
}
<h1>Service Example</h1>
<ul>
    <li><a asp-controller="CalcService" asp-action="ByModel">Using Model Calc</a></li>
    <li><a asp-controller="CalcService" asp-action="ByViewData">Using ViewData Calc</a></li>
    <li><a asp-controller="CalcService" asp-action="ByViewBag">Using ViewBag Calc</a></li>
    <li><a asp-controller="CalcService" asp-action="ByDirect">Using Service Injection Calc</a></li>
</ul>

app/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <link rel="stylesheet" href="~/css/main.css" asp-append-version="true"/>
    <title>@ViewBag.Title</title>
</head>
<body>
<header>
    <h2>Backend1</h2>
    <nav><a asp-controller="CalcService" asp-action="Index">Home</a></nav>
</header>
<main>
    @RenderBody()
</main>
<footer>
    <hr/>
    © 2021 - backend
</footer>
</body>
</html>